obytes/react-native-template-obytes

template/.github/ISSUE_TEMPLATE.md, template/.github/PULL_REQUEST_TEMPLATE.md, template/.github/workflows/android_build.yml, template/.github/workflows/ios_build.yml, template/.github/workflows/lint.yml, template/README.md, template/package.json, template/yarn.lock
* Setup GitHub actions
* Setup a releasing workflow using `release-it`
=> feat: setup Github action to build IOS and android

template/package.json, template/src/ui/Button.tsx, template/yarn.lock
=> chore: migrate restyle

docs/docs/stay-updated.md
- Remove dead links
- Organize by categories of resources
Some links were outdated
**before** 
**after**
https://starter.obytes.com/docs/stay-updated
=> docs: update ressources link

README.md
_Describe what your changes **do**; did you add a $COOL_FEATURE? Write about it here._
_**Why** did you make these changes? This is your opportunity to provide the rationale that drove the design of your solution._
_Does your code affect something downstream? Are there side effects people should know about? Tag any developers that should be kept abreast of this change._
_How did you test your change? Document it here._
=> chore: fix writing react native svg lib

package.json
fix conflict that occurs after running expo doctor 
Locally Manually
=> fix: conflict with node_modules np

docs/docs/ui-and-theme/components.mdx
=> docs: fix typos

src/screens/login/index.tsx, src/screens/login/login-form.test.tsx, src/screens/login/login-form.tsx
fix failed test in the login form 
running unit test 
According to the documentation, there's a second argument that doesn't get pass the unit test (event) 
https://react-hook-form.com/api/useform/handlesubmit/#main
=> fix: login form failed test

src/ui/core/input/controlled-input.tsx
=> fix missed ref on controlled input

.github/PULL_REQUEST_TEMPLATE.md, .github/actions/setup-node-pnpm-install/action.yml, .github/workflows/compress-images.yml, .github/workflows/expo-doctor.yml, .github/workflows/lint-ts.yml, .github/workflows/production-build.yaml, .github/workflows/qa-build.yaml, .github/workflows/test.yml, .github/workflows/type-check.yml, docs/docs/stay-updated.md
This pull request is a simple refactoring for GitHub Actions. It uses a composite action to set up Node.js and PNPM, and also installs project dependencies.
With this update, you can easily modify the logic of project setup, and it should be reflected in all workflows as a whole. For example, if you want to switch to Yarn.
This pull request introduces a straightforward workflow to build the app with ease for iOS and Android.
=> Refactor GitHub workflow and add more workflows.

src/navigation/focus-aware-status-bar.tsx, src/navigation/index.tsx, src/screens/feed/list.tsx, src/screens/feed/post.tsx, src/screens/login/index.tsx, src/screens/onboarding/onboarding.tsx, src/screens/settings/index.tsx, src/screens/style/index.tsx, src/ui/core/index.tsx, src/ui/core/modal/dynamic-modal.tsx, src/ui/core/modal/index.tsx, src/ui/core/modal/modal-backdrop.tsx, src/ui/core/modal/modal-header.tsx, src/ui/core/modal/modal.tsx, src/ui/core/modal/types.ts, src/ui/core/modal/x-close.tsx, src/ui/core/select/icons.tsx, src/ui/core/select/options.tsx
* New modal component based on bottom sheet with dynamic height.
* Fix status bar styling on dark mode 
* more fixes 
Most of the projects we work on require a Modal component as well as a Select component.
NA
Locally
=> Modal-core-component

README.md
Documentation links were broken
=> fix(docs): update documentation links

README.md, docs/src/content/docs/overview.md
Fix this the duplicated text:
[post link](https://starter.obytes.com/overview/)
...
no risks or negative impact
locally
=> fix(docs): typo in the overview post

docs/src/content/docs/overview.md
=> docs: fixed a typo

docs/astro.config.mjs, docs/package.json, docs/pnpm-lock.yaml, docs/src/components/Comments.astro, docs/src/components/LastUpdated.astro, docs/src/content/docs/index.mdx
Add comments section to documentation website
=> feat: add comments section to docs website

package.json, pnpm-lock.yaml
This pull request resolves Issue [#229](https://github.com/obytes/react-native-template-obytes/pull/229)
=> chore: update bottom-sheet

README.md, docs/src/content/docs/getting-started/project-structure.mdx, docs/src/content/docs/overview.md, docs/src/content/docs/ui-and-theme/Forms.mdx, docs/src/content/docs/ui-and-theme/components.mdx, docs/src/content/docs/ui-and-theme/fonts.mdx, docs/src/content/docs/ui-and-theme/ui-theming.mdx
=> docs: update docs

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/build.gradle, android/gradle.properties, ios/ObytesApp.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, pnpm-lock.yaml, src/components/inputs.tsx, src/ui/core/checkbox.tsx, src/ui/core/select.tsx, src/ui/icons/caret-down.tsx
- added checkbox component to ui 
- locally
=> feat: add checkbox component

.vscode/settings.json
Enable auto-complete/highlights for Tailwind variants in VSCode.
=> feat: IntelliSense for TW variants

.github/workflows/compress-images.yml, .github/workflows/e2e-android-eas-build.yml, .github/workflows/e2e-android-maestro.yml, .github/workflows/e2e-android.yml, .github/workflows/eas-build-prod.yml, .github/workflows/eas-build-qa.yml, .github/workflows/expo-doctor.yml, .github/workflows/lint-ts.yml, .github/workflows/new-app-version.yml, .github/workflows/new-github-release.yml, .github/workflows/test.yml, .github/workflows/type-check.yml
=> Fix typos in GitHub Actions

docs/astro.config.mjs, docs/src/content/docs/changelog.md, docs/src/content/docs/libraries-recommendation.md
Add a new page in the documentation for recommended libraries not included in the starter.
More clarity 
NA
NA
=> feat(docs): add recommended libs guide

README.md, docs/astro.config.mjs, docs/package.json, docs/pnpm-lock.yaml, docs/src/components/GithubStar.astro, docs/src/content/docs/faq.md, docs/src/content/docs/index.mdx, docs/src/content/docs/overview.md, docs/src/content/docs/recipes/sentry-setup.mdx, docs/src/content/docs/reviews.md
This PR introduces a new section in the docs titled "Recipes" where we will add documentation for libraries that are not included in the starter but are heavily used in projects.
* Docs to setup sentry
* FAQ page
* Reviews page
* Refactor overview page and readme 
more docs
NA
NA
=> feat(docs): add sentry setup
