obytes/react-native-template-obytes

.github/workflows/notice-yarn-changes.yml, .github/workflows/validate-ts.yml, app.config.ts, config/config.js, config/index.ts
Address issue #81 
Fix bug when running `staging` or `production` locally.
=> Bugfix: Checking process.env at runtime doesn't work

package.json, pnpm-lock.yaml
Update the `app-icon-badge` library to version `0.0.13`.
Close https://github.com/obytes/react-native-template-obytes/issues/174
_Does your code affect something downstream? Are there side effects people should know about? Tag any developers that should be kept abreast of this change._
_How did you test your change? Document it here._
=> fix: Update `app-icon-badge`

eas-pre-install, package.json
fix peers dependencies installation  error due to an old version of pnpm in expo cloud build machine android 
CLI
=> fix: peers dependencies installation error 

package.json
Expo 49 allow to remove `--dev-client` from scripts
_Describe what your changes **do**; did you add a $COOL_FEATURE? Write about it here._
_**Why** did you make these changes? This is your opportunity to provide the rationale that drove the design of your solution._
_Does your code affect something downstream? Are there side effects people should know about? Tag any developers that should be kept abreast of this change._
_How did you test your change? Document it here._
=> feat: Expo 49 allow to remove --dev-client from scripts

docs/src/content/docs/getting-started/rules-and-conventions.mdx
fix typo in _post-merge_ details in _rules-and-conventions_ page 
change **yarn.lock** to **pnpm-lock.yaml** since the main package manger for this template is **pnpm** and not **yarn**.
=> docs: fix typo in post-merge details

src/screens/settings/language-item.tsx, src/screens/settings/theme-item.tsx, src/ui/core/modal/dynamic-modal.tsx, src/ui/core/modal/modal.tsx, src/ui/core/select/select.tsx
Refactor `useModal` hook to export modal ref , `present` and  `dismiss` functions  instead of only  modal `ref`. 
Whenever we use `useModalRef`, we usually need to create functions for present and dismiss. Exporting them from the hook makes using the modal much easier.
This update modifies the modal API. Therefore, if you are using the modal hook, you will need to refactor your code.
Locally
=> refactor: refactor modal component + useModal hook

cli/utils.js
Shows a message after the '📱 Run your project:` sentence saying cd into project before running
To make it clear to understand that before running, one need to cd into the project
No impact, only changes the message shown on CLI
Don't know how to test it as I need to deploy the package on NPM? I'd appreciate if a maintainer showed me.
=> CLI: update utils.js to show to cd into project before running

docs/src/content/docs/getting-started/create-new-app.md
Docs improvements
This is for https://github.com/obytes/react-native-template-obytes/issues/239 . To prevent incorrect package naming. 
Only docs
Visual testing as it is only docs improvement
---
I have added the android docs links as I came accross this problem with android but if there is an IOS naming convention, it can be added as well. Fell free to add.
=> Docs: add naming convention note for android

README.md, cli/README.md, docs/src/content/docs/getting-started/project-structure.mdx, docs/src/content/docs/guides/authentication.mdx, docs/src/content/docs/guides/data-fetching.mdx, docs/src/content/docs/guides/navigation.mdx, docs/src/content/docs/index.mdx, docs/src/content/docs/overview.md, docs/src/content/docs/testing/unit-testing.mdx, docs/src/content/docs/ui-and-theme/components.mdx, docs/src/content/docs/ui-and-theme/ui-theming.mdx
=> chore(docs): update navigation docs

docs/src/content/docs/ui-and-theme/components.mdx
- added documents for checkbox, radio & switch UI components
=> Docs for checkbox, radio & switch components

package.json, pnpm-lock.yaml
- locks tailwindcss version to 3.3.2
=> Lock tailwindcss version to 3.3.2

docs/src/content/docs/getting-started/rules-and-conventions.mdx
Fixes typo for the docs in Rules and Conventions for section Typescript (Typescript for react developers).
The current link leads to a 404
=> fix typo in link for typescript for react developers

src/ui/input.tsx
I have added textAlign property to textInput so It works fine on RTL.
Without textAlign, RTL not working perfectly on textInput.
=> (fix) TextInput RTL issue when focus

.eslintrc.js
Cycle dependencies may lead to unpredictable results especially if you
have many of them.
Add an ESLint rule to enforce checking for cyclic dependencies as an error.
NA 
Locally
=> feat: check for cycle imports

docs/src/content/docs/ci-cd/app-releasing-process.mdx, docs/src/content/docs/getting-started/environment-vars-config.mdx
Add documentation for environment variables when using GitHub Actions, in case you do not want to push environment files.
more clarity 
NA
NA
=> feat(docs): add docs for env vars with github secrets

docs/src/content/docs/getting-started/environment-vars-config.mdx, docs/src/content/docs/guides/upgrading-deps.mdx, env.js
Incorrect commands leading to CLI errors.
Everyone who reads the docs.
By running the commands.
**Before**
with `-clean` ❌
with `--cc` ❌
with `expo@lastVersion` ❌
**After**
with `--clean` ✅
with `-c` ✅
with `expo@latest` ✅
=> fix(docs): expo commands

.github/actions/setup-jdk-generate-apk/action.yml, package.json
It fixes this issue https://github.com/obytes/react-native-template-obytes/issues/370 and https://github.com/obytes/react-native-template-obytes/issues/372
I have added ```prebuild:development``` script on package.json
and added ```java-version: '17'``` in here ```.github/actions/setup-jdk-generate-apk/action.yml```
Other than solving the issue, It should not affect any other parts of this template.
I have tested with my project.
=> Fix:  ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "prebuild:developme…" and gradle plugin issue with java version

docs/src/content/docs/recipes/sentry-setup.mdx
Use the `expo install` command to ensure we are using the correct Sentry version recommended by Expo.
Fix #376
=> fix(docs): update command to install sentry

package.json, pnpm-lock.yaml, project.d.ts, scripts/eas-pre-install, src/app/+html.tsx, src/app/[...messing].tsx, src/core/hooks/use-selected-theme.tsx, tsconfig.json
Update the the last nativewind  stable version 
Upgrade + improve perf + fix web issues
Locally
=> Upgrade to latest nativewind stable version 

ios/Podfile.lock, src/components/login-form.test.tsx, src/components/login-form.tsx
Add a description on the login screen to clarify that you don't need credentials to log in, as this is a simple demo login.
#393 
More clarity 
Locally
=> feat: add more details on how to login #393

docs/src/content/docs/getting-started/create-new-app.md
This PR fixes a grammatical error in the documentation for creating a new app. There was an incomplete sentence that I have combined with the next sentence. I've also replaced the semicolon with a full stop for greater clarity.
I wanted to improve the documentation quality.
It concerns the [Create New App](https://starter.obytes.com/getting-started/create-new-app/) page.
N/A.
=> Fix grammatical error and improve sentence structure

src/components/ui/focus-aware-status-bar.tsx
- Removes SystemBars rendering on web
- SystemBars is a native-only component and was causing runtime errors in browser
- Fixes web application crashes
- No changes to native mobile functionality
- Verified web app loads without crashes
- Confirmed native StatusBar still works on iOS/Android
=> fix: fix focuse aware statue bar crash in web

docs/src/content/docs/guides/authentication.mdx
Fix a small typo in the guides for authentication section.
I was reading the docs when I discovered this tiny issue so I decided to inform you about it. The second reason is the love of open source I like to be a part of it even for a small fix like this one.
This will improve the readability of the docs and ultimately improve the starter which I absolutely like and use.
It's only a typo in text no need for test I guess 🤗
=> fix(docs): fix typo in authentication guides docs

docs/src/content/docs/guides/upgrading-deps.mdx
Solves a typo error in docs.
I was reading the docs and found this typo and thought to correct it as my contribution to this great repo.
Documents->Guides->Upgrade Dependencies
By my eyes.
=> typo(docs): Change sur to sure
